add monatsbericht september 24
temporaerhaus/website pull request #61
Opened 2024-10-09 19:49 UTC by stkdiretto

2024-10-09 19:57 UTC, FelixWohlfrom requested changes

2024-10-09 19:57 UTC, FelixWohlfrom commented on content/posts/2024-20-10-ein-jahr-am-neuen-ort.de.md
> +---
ich glaub die datei kann weg :)

2024-10-09 20:46 UTC, stkdiretto commented on content/posts/2024-20-10-ein-jahr-am-neuen-ort.de.md
> +---
andersrum, die 10er-Datei war das Problem. Danke!

2024-10-10 16:57 UTC, FelixWohlfrom approved these changes

2024-10-10 16:57 UTC, merged